apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stackedit.fullname" . }}
  labels:
{{ include "stackedit.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "stackedit.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "stackedit.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: /run
              name: run-volume
            - mountPath: /tmp
              name: tmp-volume
          env:
            - name: PORT
              value: "8080"
            - name: EXPORT_MAX_CONCURRENT
              value: {{ .Values.exportMaxConcurrent | quote }}
            - name: EXPORT_MAX_INPUT_BYTES
              value: {{ .Values.exportMaxInputBytes | quote }}
            - name: EXPORT_REMOTE_HOSTS
              value: {{ .Values.exportRemoteHosts | quote }}
            - name: EXPORT_TIMEOUT_MS
              value: {{ .Values.exportTimeoutMs | quote }}
            - name: PAYPAL_RECEIVER_EMAIL
              value: {{ .Values.paypalReceiverEmail | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "stackedit.secretName" . }}
                  key: awsAccessKeyId
                  optional: true
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "stackedit.secretName" . }}
                  key: awsSecretAccessKey
                  optional: true
            - name: DROPBOX_APP_KEY
              value: {{ .Values.dropboxAppKey | quote }}
            - name: DROPBOX_APP_KEY_FULL
              value: {{ .Values.dropboxAppKeyFull | quote }}
            - name: GOOGLE_CLIENT_ID
              value: {{ .Values.googleClientId | quote }}
            - name: GOOGLE_API_KEY
              value: {{ .Values.googleApiKey | quote }}
            - name: GITHUB_CLIENT_ID
              value: {{ .Values.githubClientId | quote }}
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "stackedit.secretName" . }}
                  key: githubClientSecret
                  optional: true
            - name: WORDPRESS_CLIENT_ID
              value: {{ .Values.wordpressClientId | quote }}
            - name: WORDPRESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "stackedit.secretName" . }}
                  key: wordpressSecret
                  optional: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: run-volume
        emptyDir: {}
      - name: tmp-volume
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
