{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackedit.secretName" . }}
  labels:
{{ include "stackedit.labels" . | indent 4 }}
type: Opaque
stringData:
  awsAccessKeyId: {{ .Values.awsAccessKeyId | quote }}
  awsSecretAccessKey: {{ .Values.awsSecretAccessKey | quote }}
  githubClientSecret: {{ .Values.githubClientSecret | quote }}
  wordpressSecret: {{ .Values.wordpressSecret | quote }}
{{- end }}
