name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22.x
          - 24.x
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci --legacy-peer-deps
      - run: npm test

  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      CHARTS_GITHUB_TOKEN: ${{ secrets.CHARTS_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: npm
      - run: npm ci --legacy-peer-deps
      - run: docker build -t benweet/stackedit .
      - uses: azure/setup-helm@v4
      - run: bash build/deploy.sh
